# Generated by Django 3.1.1 on 2020-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionX', models.TextField()),
                ('positionY', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
