# Generated by Django 3.1.2 on 2020-10-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_fill', models.CharField(max_length=10)),
                ('original_stroke', models.CharField(max_length=10)),
                ('original_stroke_width', models.FloatField()),
                ('original_style', models.CharField(max_length=30)),
                ('original_x1', models.FloatField()),
                ('original_y1', models.FloatField()),
                ('original_x2', models.FloatField()),
                ('original_y2', models.FloatField()),
                ('original_id', models.CharField(max_length=20)),
                ('original_type', models.CharField(max_length=15)),
                ('original_stroke_linejoin', models.CharField(blank=True, max_length=30, null=True)),
                ('original_stroke_linecap', models.CharField(blank=True, max_length=30, null=True)),
                ('original_stroke_dasharray', models.CharField(blank=True, max_length=30, null=True)),
                ('new_fill', models.CharField(max_length=10)),
                ('new_stroke', models.CharField(max_length=10)),
                ('new_stroke_width', models.FloatField()),
                ('new_style', models.CharField(max_length=30)),
                ('new_x1', models.FloatField()),
                ('new_y1', models.FloatField()),
                ('new_x2', models.FloatField()),
                ('new_y2', models.FloatField()),
                ('new_id', models.CharField(max_length=20)),
                ('new_type', models.CharField(max_length=15)),
                ('new_stroke_linejoin', models.CharField(blank=True, max_length=30, null=True)),
                ('new_stroke_linecap', models.CharField(blank=True, max_length=30, null=True)),
                ('new_stroke_dasharray', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
