# Generated by Django 3.1.2 on 2020-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='filename',
            field=models.CharField(default='page_6_table_1.svg', max_length=40),
            preserve_default=False,
        ),
    ]
