# Generated by Django 3.1.1 on 2020-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='positionX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vector',
            name='positionY',
            field=models.FloatField(),
        ),
    ]
