# Generated by Django 3.1.2 on 2020-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors_db', '0002_vector_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='new_fill_opacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vector',
            name='new_stroke_opacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
