# Generated by Django 3.1.1 on 2020-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors_db', '0003_auto_20200926_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='fill',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vector',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vector',
            name='shape_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vector',
            name='stroke',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vector',
            name='stroke_dasharray',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='stroke_linecap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='stroke_linejoin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='style',
            field=models.CharField(max_length=30),
        ),
    ]
