# Generated by Django 3.1.1 on 2020-10-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors_db', '0004_auto_20200927_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vector',
            old_name='fill',
            new_name='original_fill',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='id_number',
            new_name='original_id',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='stroke',
            new_name='original_stroke',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='stroke_dasharray',
            new_name='original_stroke_dasharray',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='stroke_linecap',
            new_name='original_stroke_linecap',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='stroke_linejoin',
            new_name='original_stroke_linejoin',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='stroke_width',
            new_name='original_stroke_width',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='style',
            new_name='original_style',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='shape_type',
            new_name='original_type',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='x1',
            new_name='original_x1',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='x2',
            new_name='original_x2',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='y1',
            new_name='original_y1',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='y2',
            new_name='original_y2',
        ),
    ]
