from django.db import models


# Create your models here.
class Vector(models.Model):
  filename = models.CharField(max_length=40)
  original_fill = models.CharField(max_length=10, null=True)
  original_stroke = models.CharField(max_length=10, null=True)
  original_stroke_width = models.FloatField(null=True)
  original_style = models.CharField(max_length=30, null=True)
  original_x1 = models.FloatField(null=True)
  original_y1 = models.FloatField(null=True)
  original_x2 = models.FloatField(null=True)
  original_y2 = models.FloatField(null=True)
  original_id = models.CharField(max_length=20, null=True)
  original_type = models.CharField(max_length=15, null=True)
  original_stroke_linejoin = models.CharField(max_length=30, null=True, blank=True)
  original_stroke_linecap = models.CharField(max_length=30, null=True, blank=True)
  original_stroke_dasharray = models.CharField(max_length=30, null=True, blank=True)
  
  new_fill = models.CharField(max_length=10)
  new_stroke = models.CharField(max_length=10)
  new_stroke_width = models.FloatField()
  new_style = models.CharField(max_length=30)
  new_x1 = models.FloatField()
  new_y1 = models.FloatField()
  new_x2 = models.FloatField()
  new_y2 = models.FloatField()
  new_id = models.CharField(max_length=20)
  new_type = models.CharField(max_length=15)
  new_stroke_linejoin = models.CharField(max_length=30, null=True, blank=True)
  new_stroke_linecap = models.CharField(max_length=30, null=True, blank=True)
  new_stroke_dasharray = models.CharField(max_length=30, null=True, blank=True)
  new_stroke_opacity = models.CharField(max_length=30, null=True, blank=True)
  new_fill_opacity = models.CharField(max_length=30, null=True, blank=True)
